### PR TITLE
Use list instead of set as requested in issue #10

### PR DESCRIPTION
**Pull request by kiwifb**

### CODE REVIEW

**Comment by kiwifb** [comment]
If there are cases where set are really useful, I would be happy to offer list output as a new interface instead.

**Comment by kiwifb** [comment]
It also appears that the tests are misconfigured. I didn't really check that.

**Comment by matze** [comment]
I removed `--use-mirrors` from the Travis description. Could you rebase  and preferably squash the two commits and force push them?

**Comment by kiwifb** [comment]
I'll rebase, about the squashing github offer you that has an option for merging these days. But if you insist, I'll work it out.

**Comment by matze** [comment]
It's not about merging, it's about having only a clean single commit for the single change that is.

**Comment by kiwifb** [comment]
Did it the brutal way but the history should be clean and simple.

**Comment by matze** [comment]
Thanks! And thanks for the contribution.

**Pull request merged**
