### PR TITLE
clean up, update version and changelog

### PR DESCRIPTION
**Pull request by ThomasWaldmann**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
@matze Not sure how you do versioning here, will 1.5.6 be the next release?

**Comment by matze** [comment]
I think those changes (more than just fixes) warrant a 1.6.0.

**Comment by ThomasWaldmann** [comment]
OK, changed version to 1.6.0.

**Comment by ThomasWaldmann** [comment]
OK, ready for review/merge.

**Pull request merged**
